server:
  port: 9100
  servlet:
    context-path: /@project.name@
spring:
 profiles:
   active: @env@
 security:
   user:
     name: admin
     password: test1234

 cloud:
   zookeeper:
     connect-string: localhost:2182

 application:
   name: zookeeper-test
