server:
  port: 8087
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'
 security:
   user:
     name: admin
     password: test1234

eureka:
  instance: # eureak实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 60000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式，保护模式是指服务在掉线后不立马清除服务
  client:
    register-with-eureka: false #是否注册到eureka
    fetch-registry: false #指示此客户端是否应从eureka服务器获取eureka注册表信息
    service-url: #高可用配置
#      defaultZone: http://admin:test1234@localhost:8087/springcloud-eureka/eureka
      defaultZone: http://admin:test1234@eureka1:8087/eureka,http://admin:test1234@eureka2:8090/eureka
