apiVersion: v1
kind: Pod
metadata:
  name: mysql #pod的名称
  namespace: default
  labels:
    component: mysql
spec:
  #hostNetwork: true	# 声明pod的网络模式为host模式，效果通docker run --net=host
  volumes:
    - name: mysql-data
      hostPath:
        path: /opt/mysql/data
  nodeSelector:   # 使用节点选择器将Pod调度到指定label的节点
    component: mysql
  containers:
    - name: mysql
      image: daocloud.io/library/mysql:5.7.4
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          # 使用环境变量
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWD
        - name: MYSQL_USER
          value: "test"  # mysql 用户名
        - name: MYSQL_PASSWORD
          value: "test"  # mysql 密码
      resources:
        requests:
          memory: 100Mi
          cpu: 50m
        limits:
          memory: 200Mi
          cpu: 100m
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: mysql
  name: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodeport: 30001 #手动指定nodeport（只针对type 为NodePort形式）
  selector: #关联pod
    component: mysql
  type: NodePort