server:
  port: 8081
  servlet:
    context-path: /@project.name@
spring:
 profiles:
   active: @env@
 datasource:
  druid:
    filter:
      stat:
        log-slow-sql: true #是否打印慢sql
        merge-sql: true #是否合并sql
    stat-view-servlet:
      enable: true
      allow: 192.168.0.4 #ip 容许列表
      loginUsername: root
      loginPassword: test1234
 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码

mybatis-plus:
  mapperLocations: classpath:/sqlMapperXml/**/*.xml

