server:
  port: 8081
  servlet:
    context-path: /@project.name@
spring:
 profiles:
   active: @env@
 datasource:
  druid:
    filter:
      stat:
        log-slow-sql: true
        merge-sql: true
 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码

mybatis-plus:
  mapperLocations: classpath:/sqlMapperXml/**/*.xml

