server:
  port: 8095
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'
 application:
  name: springcloud-config-server
 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
 cloud:
   config:
     server:
       git:
         uri: https://github.com/ypdaic/springcloud-config.git


