server:
  port: 8086
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:test1234@eureka1:8087/eureka,http://admin:test1234@eureka2:8090/eureka
ribbon:
  eager-load: #配置饥饿加载，也就是启动时就去初始化ribbonClient，否则是在调用时才初始化。代码做了同步处理NamedContextFactory 99行
    enabled: true
    clients: springcloud-provider
  ConnectTimeout: 4000  #给RibbonProperties使用
  ReadTimeout: 4000  #给RibbonProperties使用


