server:
  port: 8086
  servlet:
    context-path: /@project.name@
spring:
 profiles:
   active: @env@

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:test1234@eureka1:8087/springcloud-eureka/eureka,http://admin:test1234@eureka2:8090/springcloud-eureka2/eureka

