server:
  port: 8092
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'
 zipkin:
   base-url: http://localhost:8601/ #所有的服务提交到此服务中
   sender:
     type: rabbit #提交的类型是rabbit 服务
#     type: web #提交的类型是web 服务
 sleuth:
   sampler:
     probability: 1.0 #定义抽样比率，默认为0.1
 # zipkin sender需要
 rabbitmq:
   host: 192.168.111.128
   port: 5672
   password: test1234
   username: root
   virtual-host: /
 application:
   name: springcloud-consumer
eureka:
  client:
    register-with-eureka: false
    service-url:
#      defaultZone: http://admin:test1234@eureka1:8098/eureka
      defaultZone: http://admin:test1234@eureka1:8087/eureka,http://admin:test1234@eureka2:8090/eureka
feign:
  hystrix:
    enabled: true # 启用hystrix
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩