server:
  port: 8092
  servlet:
    context-path: /@project.name@
spring:
 profiles:
   active: @env@

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:test1234@eureka1:8087/springcloud-eureka/eureka,http://admin:test1234@eureka2:8090/springcloud-eureka2/eureka
feign:
  hystrix:
    enabled: true # 启用hystrix
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩