#开发配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
##    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
configuration-properties-test:
  name: 这是我的自定配置

spring:
  redis:
    host: 127.0.0.1
    port: 6379
