#开发配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
##    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
configuration-properties-test:
  name: 这是我的自定配置
server:
  port: 8081
spring:
  profiles:
    active: dev

  cache:
    redis:
      #redis 缓存过期时间，1天
      time-to-live: 1d
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: myscheduling-

  # spring 默认开启Redis的repositories支持，这个会默认开启一个RedisMessageListenerContainer，我们先关闭该功能
  data:
    redis:
      repositories:
        enabled: false
  jta:
    enabled: true
  transaction:
    defaultTimeout: 1000
    rollbackOnCommitFailure: true

  mail:
    username: 841943896@qq.com
    password: uinilqpqenjrbeic
    host: smtp.qq.com
    port: 587




#查看自动配置的加载情况
#debug: true


