#开发配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
##    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
configuration-properties-test:
  name: 这是我的自定配置

spring:
  profiles:
    active: dev

  cache:
    redis:
      #redis 缓存过期时间，1天
      time-to-live: 1d
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: myscheduling-

