server:
  port: 10001
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'
 application:
  name: springcloud-oauth2 #设置应用名称
 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
      host: 192.168.184.128
      port: 6379
      password: test1234

info:
  app.name: '@project.name@'
  company.name: daiyanping
  build.artifactId: '@project.artifactId@'
  build.modelVersion: '@project.modelVersion@'

