groups:
- name: prometheus_alerts
  rules:
  - alert: PrometheusConfigReloadFailed #配置加载错误报警
    expr: prometheus_config_last_reload_successful == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Reloading Prometheus configuration has failed on {{ $labels.instance }}.
  - alert: PrometheusNotConnectedToAlertmanagers #alertmanagers 连接失败报警
    expr: prometheus_notifications_alertmanagers_discovered < 2
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Prometheus {{ $labels.instance }} is not connected to any Alertmanagers