server:
  port: 8094
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'
 application:
  name: springcloud-zuul-gateway
 zipkin:
   base-url: http://localhost:8601/ #所有的服务提交到此服务中
   sender:
     type: RABBIT #提交的类型是rabbit 服务
#     type: web #提交的类型是web 服务
 sleuth:
   sampler:
     probability: 1.0 #定义抽样比率，默认为0.1
 # zipkin sender需要
 rabbitmq:
   host: 192.168.111.128
   port: 5672
   password: test1234
   username: root
   virtual-host: /

 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码

# 将服务注册到eureka上
eureka:
  client:
    serviceUrl:
      # 单例
      #defaultZone: http://admin:test1234@localhost:8087/springcloud-eureka/eureka/

      # 高可用
      defaultZone: http://admin:test1234@eureka1:8087/eureka,http://admin:test1234@eureka2:8090/eureka
  instance: #zuul注册到erake上，使其可以被消费者客户端发现
    instanceId: zuul
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: '@project.name@'
  company.name: daiyanping
  build.artifactId: '@project.artifactId@'
  build.modelVersion: '@project.modelVersion@'

zuul:
  routes:
    users:
      path: /users-proxy/**
      serviceId: springcloud-user
    users2: #不通过eureka访问
      path: /users2-proxy/**
      url: http://localhost:8095/
    product: #产品的路由，访问：http://localhost:8094/zuul/product-proxy/product/getProduct，如果加了公共前缀，这需要加前缀
      path: /product-proxy/**
      serviceId: springcloud-provider
  ignored-services: #禁止直接通过服务名访问，如：http://localhost:8094/zuul/springcloud-provider/product/getProduct
    "*"
  prefix: /zuul-api #设置公共前缀，设置后所有请求都要加上该前缀，如果不加就会404 如：http://localhost:8094/zuul/zuul-api/product-proxy/product/getProduct
  sensitive-headers: "Cookie,Set-Cookie" #设置不向下游服务器传递的heads，默认为"Cookie", "Set-Cookie", "Authorization"

