server:
  port: 8092
  servlet:
    context-path: /
spring:
 profiles:
   active: '@env@'

ribbon:
  eureka:
    enabled: false

SPRINGCLOUD-PROVIDER:
  ribbon:
    listOfServers: http://localhost:8088,http://localhost:8091
